auto: true
server: true
highlighter: rouge
permalink: none
root_dir: ""
oauth_client_id: caf55c20366465a1332d
gatekeeper_url: http://poole-oauth-staging.herokuapp.com
exclude:
- .gitignore
- README.md
